# Generated by Django 5.2.7 on 2025-12-13 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_answer_count_question_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='rating',
            new_name='rating_cache',
        ),
    ]
