# Generated by Django 5.2.7 on 2025-12-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_rating_question_rating_cache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_count',
            new_name='answer_count_cache',
        ),
    ]
