# Generated by Django 5.2.7 on 2025-12-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_answer_count_question_answer_count_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating_cache',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question'),
        ),
    ]
